### PR TITLE
fix broken build stemming from 369b086

### PR DESCRIPTION
**Pull request by fkuehlein**
commit 369b086 caused builds to fail due to:
- **lint**: newly introduced pylint flag `possibly-used-before-assignment` (resolved with bc41360)
- **docs**: not sure, could not reproduce locally. might be something related to version updates as well. will check here by reverting the commit that caused it.

### CODE REVIEW

**Comment by fkuehlein** [comment]
So the failing build was definitely was not caused by 369b086 itself, as the revert didn't fix it.

In fact, I could now reproduce breaking change in `docutils>=0.21` affecting the (apparently unmaintained) `nbsphinx-link` package: 

```
  File "/opt/miniconda3/envs/pyunicorn_docs/lib/python3.12/site-packages/nbsphinx_link/__init__.py", line 192, in parse
    path = nodes.reprunicode(path)
           ^^^^^^^^^^^^^^^^^
AttributeError: module 'docutils.nodes' has no attribute 'reprunicode'
```

Indeed, `docutils.node.reprunicode` was dropped with `docutils` v0.21.0 as it was a ['Python 2 compatibility hack'](https://docutils.sourceforge.io/RELEASE-NOTES.html#release-0-21-2024-04-09). Just made a respectiv respective [PR to `nbsphinx-link`](https://github.com/vidartf/nbsphinx-link), but need to find an alternative to resolve this.

Therefore dropped `nbsphinx-link` dependency and move examples folder into docs with c54102e.
